update to give a notice to unplug
antonvh/mpy-robot-tools pull request #2
Opened 2022-01-20 04:06 UTC by SpudGunMan

little helper notice to unplug USB

2022-01-20 08:40 UTC, antonvh commented
Thanks! I will have a look at it tonight.

2022-01-20 19:25 UTC, SpudGunMan commented
there is random hash failure that was not trapped before, I haven't looked to see why the file hashes on Ctrl_plus and husky libs commonly fail a hash check, I will have it work fine once then fail for like a dozen times then work again fine. the chunking seems ok and the file is written to flash on the hub and all...

2022-01-21 02:03 UTC, SpudGunMan commented
your installer was nice and I ported it out into its own to manage multiple projects feel free to take these files you can just drop off the 3rd party projects, I was going to add a function to copy binary files as well for support...
https://github.com/SpudGunMan/SpudGunMan/tree/main/Lego/legolibs

2022-01-22 20:16 UTC, antonvh approved these changes

2022-01-22 20:17 UTC, antonvh reviewed
Did you have trouble with this? If a file exists python just overwrites it, no need to remove the old one. Why did you add this?

2022-01-22 20:25 UTC, antonvh requested changes
I like the BAD_NAMES solution. I also like the renaming of the encoded variable. I like the readme update. But the lib should be solved differently. In the future it is better to create a different commit for every change. For now, can you do a new PR with only the changes that are ok? I will add the uartremote lib myself.

2022-01-22 20:25 UTC, antonvh commented on Installer/create_install_script.py
> +LIB_UART = '../../LMS-uart-esp/Libraries/UartRemote/MicroPython/uartremote.py'
Please remove this. I would like to do this with a git submodule. That's more reliable.

2022-01-22 20:30 UTC, antonvh requested changes
Great, thanks. Except for sleep_ms -> sleep. I don't see the point?

2022-01-22 20:33 UTC, antonvh commented
> your installer was nice and I ported it out into its own to manage multiple projects feel free to take these files you can just drop off the 3rd party projects, I was going to add a function to copy binary files as well for support...

It would be nice if we could solve this in a general way. The installer could be a drop-in git submodule that scans a library folder for files and generates the scripts.

2022-01-23 01:22 UTC, SpudGunMan commented
Hey I agree, this was a bit of a mess I was just trying to port up your script so I could quickly rebuild a stack of bricks without having to maintain updates etc.. 

 added the timeouts which seemed to help with some hash calculation issues. 

The fork I did was really my end goal and it now compiles all your stuff into a single directory and if its interesting to you I would take it ... also as you mentioned might just be worth putting all libs in one place so when you add more libs to it as you mentioned it will just compile them all..

2022-01-23 04:49 UTC, SpudGunMan commented
not sure if you want to consider this fork, I sort of made a mess with starting edits to your installer here when it works just fine for your stuff and there is no real reason to take any of these changes check out..
https://github.com/SpudGunMan/SpudGunMan/blob/main/Lego/legolibs/create_install_script.py

2022-01-23 21:10 UTC, SpudGunMan commented
to fully answer the why did I add a time.wait. was because I was having error I didn't trap yet.

I was following symlinks on osx/alias. it was a messy way to error check. I did away with following links as jumping project to project with them isn't working on my end anyway...

2022-01-24 07:40 UTC, antonvh commented
If you don't mind, I'll cherry-pick some of your changes and move the whole installer to a drop-in submodule, sometime this week.

2022-01-25 04:43 UTC, closed without merging